[window]
title = "Alacritty"
dynamic_title = true
decorations = "Full"

[font]
# FiraMono nerd font fixes glyphes
normal = { family = "FiraMono Nerd Font Mono", style = "Regular"}
bold = {family = "FiraMono Nerd Font Mono"}
italic = {family = "FiraMono Nerd Font Mono"}
bold_italic = {family = "FiraMono Nerd Font Mono"}
size = 7

[colors]
primary.background = '0x232136'
